### ISSUE TITLE
port_scanner - Use of uninitialized value in subroutine entry

### ISSUE THREAD

**Issue by jreisinger** [dnmfarrell/Penetration-Testing-With-Perl#2]
I get the following error when running `port_scanner` against localhost:

```
$ ./port_scanner --ip 127.0.0.1

./port_scanner  Version 0.02  Source: github.com/dnmfarrell/Penetration-Testing-With-Perl

Wed Mar  9 15:52:40 2016

Starting port scan: type: tcp, flags: syn, 50 procs, 1 (secs) delay
Source host: XX.XX.XX.XX:42283, target host: 127.0.0.1

Use of uninitialized value in subroutine entry at ./port_scanner line 154, <$port_file> line 19941.
Use of uninitialized value in subroutine entry at ./port_scanner line 154, <$port_file> line 19941.
p is not of type pcap_tPtr at ./port_scanner line 154, <$port_file> line 19941.
```

**Comment by dnmfarrell** [comment]
Sorry the docs aren't clearer, you need root privileges. Are you using system Perl or a locally installed Perl? This should work for both:

```
sudo $(which perl) port_scanner --ip 127.0.0.1
```

If system Perl that can be shortened to:

```
 sudo perl port_scanner --ip 127.0.0.1
```

I'll add a check for root privileges and an exit with appropriate error message if not run as root.

**Comment by dnmfarrell** [comment]
Fixed with latest [commit](https://github.com/dnmfarrell/Penetration-Testing-With-Perl/commit/6e9706d79181d78616731b151e70e07b7e72ad33)
